language: ruby

services:
  - postgresql

before_install:
  - gem install bundler

script:
  - bundle exec rspec spec/controllers/application_controller.rb

after_script:
  - bundle exec rake coveralls:push
